// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ar.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ar', {
    "CWP.SPECIFYALTTEXT": "%s ليس لها نص بديل وهو مطلوب للصور غير المزخرفة.\n\nهل أنت متأكد أنك تريد التحديث؟"
});
}