// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/zh.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('zh', {
    "CWP.SPECIFYALTTEXT": "%s 没有非装饰性图片所要求的 alt 文本。\n您确定要更新吗？"
});
}