---
Name: standardseditingconfig
After: 'framework/*','cms/*'
---
DBField:
  extensions:
   - RichLinksExtension
Group:
  extensions:
   - StandardsHtmlEditorConfig
HtmlEditorField_Toolbar:
  extensions:
   - CustomHtmlEditorFieldToolbar
