---
Name: cwpcoreconfig
After: 'framework/*','cms/*'
---
DBField:
  extensions:
   - RichLinksExtension
Controller:
  extensions:
   - CwpControllerExtension
Group:
  extensions:
   - CwpHtmlEditorConfig
HtmlEditorField_Toolbar:
  extensions:
   - CustomHtmlEditorFieldToolbar
GDBackend:
  default_quality: 90
LeftAndMain:
  extra_requirements_css:
   - 'cwp/css/custom.css'
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
PasswordField:
  autocomplete: false
Security:
  login_recording: false
Member:
  lock_out_after_incorrect_logins: 5
  lock_out_delay_mins: 15
